app = "mamkaca-api"

primary_region = "ams"  # np. Amsterdam – możesz zmienić na coś bliższego Tobie

[build]
builder = "paketobuildpacks/builder:base"  # Fly.io używa buildpacków do budowy JAR

[env]
JAVA_OPTS = "-Xmx512m"  # Przykładowe limity pamięci JVM

[http_service]
internal_port = 8080  # Port na którym Spring Boot nasłuchuje
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[services]]
protocol = "tcp"
internal_port = 8080

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "10s"
restart_limit = 0